In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sms

In [3]:
pip install shap

WARNING: Ignoring invalid distribution ~umpy (c:\Users\Ghulam-Hur\AppData\Local\Programs\Python\Python312\Lib\site-packages)
ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\Ghulam-Hur\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numba\\cuda\\tests\\cudadrv\\test_linker.py'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting shap
  Downloading shap-0.52.0-cp312-abi3-win_amd64.whl.metadata (26 kB)
Collecting numpy>=2 (from shap)
  Using cached numpy-2.5.3-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: scipy in c:\users\ghulam-hur\appdata\local\programs\python\python312\lib\site-packages (from shap) (1.17.1)
Requirement already satisfied: scikit-learn in c:\users\ghulam-hur\appdata\local\programs\python\python312\lib\site-packages (from shap) (1.5.0)
Requirement already satisfied: pandas in c:\users\ghulam-hur\appdata\local\programs\python\python312\lib\site-packages (from shap) (2.2.2)
Collecting tqdm>=4.27.0 (from shap)
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: packaging>20.9 in c:\users\ghulam-hur\appdata\roaming\python\python312\site-packages (from shap) (26.2)
Collecting slicer==0.0.8 (from shap)
  Downloading slicer-0.0.8-py3-none-any.whl.metadata (4.0 kB)
Collecting numba (from shap)
  Downloading numba-0.67.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Collecting llvmlite (from shap)
  Downloading llvmlite-0.49.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Collecting cloudpickle (from shap)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: colorama in c:\users\ghulam-hur\appdata\roaming\python\python312\site-packages (from tqdm>=4.27.0->shap) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ghulam-hur\appdata\local\programs\python\python312\lib\site-packages (from pandas->shap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ghulam-hur\appdata\local\programs\python\python312\lib\site-packages (from pandas->shap) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ghulam-hur\appdata\local\programs\python\python312\lib\site-packages (from pandas->shap) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\ghulam-hur\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn->shap) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\ghulam-hur\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn->shap) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\ghulam-hur\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas->shap) (1.17.0)
Downloading shap-0.52.0-cp312-abi3-win_amd64.whl (499 kB)
Downloading slicer-0.0.8-py3-none-any.whl (15 kB)
Downloading numpy-2.5.3-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 2.4 MB/s eta 0:00:06
   - -------------------------------------- 0.5/12.6 MB 2.4 MB/s eta 0:00:06
   - -------------------------------------- 0.5/12.6 MB 2.4 MB/s eta 0:00:06
   -- ------------------------------------- 0.8/12.6 MB 745.8 kB/s eta 0:00:16
   -- ------------------------------------- 0.8/12.6 MB 745.8 kB/s eta 0:00:16
   -- ------------------------------------- 0.8/12.6 MB 745.8 kB/s eta 0:00:16
   ---- ----------------------------------- 1.3/12.6 MB 780.2 kB/s eta 0:00:15
   ---- ----------------------------------- 1.3/12.6 MB 780.2 kB/s eta 0:00:15
   ---- ----------------------------------- 1.3/12.6 MB 780.2 kB/s eta 0:00:15
   ----- ---------------------------------- 1.8/12.6 MB 780.2 kB/s eta 0:00:14
   ----- ---------------------------------- 1.8/12.6 MB 780.2 kB/s eta 0:00:14
   ----- ---------------------------------- 1.8/12.6 MB 780.2 kB/s eta 0:00:14
   ------ --------------------------------- 2.1/12.6 MB 711.8 kB/s eta 0:00:15
   ------- -------------------------------- 2.4/12.6 MB 725.4 kB/s eta 0:00:15
   ------- -------------------------------- 2.4/12.6 MB 725.4 kB/s eta 0:00:15
   -------- ------------------------------- 2.6/12.6 MB 732.9 kB/s eta 0:00:14
   -------- ------------------------------- 2.6/12.6 MB 732.9 kB/s eta 0:00:14
   --------- ------------------------------ 2.9/12.6 MB 696.1 kB/s eta 0:00:14
   --------- ------------------------------ 2.9/12.6 MB 696.1 kB/s eta 0:00:14
   ---------- ----------------------------- 3.1/12.6 MB 720.9 kB/s eta 0:00:14
   ---------- ----------------------------- 3.4/12.6 MB 742.8 kB/s eta 0:00:13
   ---------- ----------------------------- 3.4/12.6 MB 742.8 kB/s eta 0:00:13
   ----------- ---------------------------- 3.7/12.6 MB 719.7 kB/s eta 0:00:13
   ------------ --------------------------- 3.9/12.6 MB 736.2 kB/s eta 0:00:12
   ------------ --------------------------- 3.9/12.6 MB 736.2 kB/s eta 0:00:12
   ------------ --------------------------- 3.9/12.6 MB 736.2 kB/s eta 0:00:12
   -------------- ------------------------- 4.5/12.6 MB 749.8 kB/s eta 0:00:11
   -------------- ------------------------- 4.5/12.6 MB 749.8 kB/s eta 0:00:11
   --------------- ------------------------ 4.7/12.6 MB 746.6 kB/s eta 0:00:11
   --------------- ------------------------ 4.7/12.6 MB 746.6 kB/s eta 0:00:11
   --------------- ------------------------ 5.0/12.6 MB 738.3 kB/s eta 0:00:11
   ---------------- ----------------------- 5.2/12.6 MB 736.1 kB/s eta 0:00:10
   ---------------- ----------------------- 5.2/12.6 MB 736.1 kB/s eta 0:00:10
   ----------------- ---------------------- 5.5/12.6 MB 732.7 kB/s eta 0:00:10
   ----------------- ---------------------- 5.5/12.6 MB 732.7 kB/s eta 0:00:10
   ------------------ --------------------- 5.8/12.6 MB 734.0 kB/s eta 0:00:10
   ------------------ --------------------- 5.8/12.6 MB 734.0 kB/s eta 0:00:10
   ------------------- -------------------- 6.0/12.6 MB 735.2 kB/s eta 0:00:09
   -------------------- ------------------- 6.3/12.6 MB 735.0 kB/s eta 0:00:09
   -------------------- ------------------- 6.3/12.6 MB 735.0 kB/s eta 0:00:09
   -------------------- ------------------- 6.6/12.6 MB 736.1 kB/s eta 0:00:09
   -------------------- ------------------- 6.6/12.6 MB 736.1 kB/s eta 0:00:09
   --------------------- ------------------ 6.8/12.6 MB 737.1 kB/s eta 0:00:08
   --------------------- ------------------ 6.8/12.6 MB 737.1 kB/s eta 0:00:08
   ---------------------- ----------------- 7.1/12.6 MB 725.8 kB/s eta 0:00:08
   ----------------------- ---------------- 7.3/12.6 MB 731.8 kB/s eta 0:00:08
   ----------------------- ---------------- 7.3/12.6 MB 731.8 kB/s eta 0:00:08
   ------------------------ --------------- 7.6/12.6 MB 726.0 kB/s eta 0:00:07
   ------------------------ --------------- 7.6/12.6 MB 726.0 kB/s eta 0:00:07
   ------------------------- -------------- 7.9/12.6 MB 721.9 kB/s eta 0:00:07
   ------------------------- -------------- 7.9/12.6 MB 721.9 kB/s eta 0:00:07
   ------------------------- -------------- 8.1/12.6 MB 720.0 kB/s eta 0:00:07
   ------------------------- -------------- 8.1/12.6 MB 720.0 kB/s eta 0:00:07
   -------------------------- ------------- 8.4/12.6 MB 719.3 kB/s eta 0:00:06
   -------------------------- ------------- 8.4/12.6 MB 719.3 kB/s eta 0:00:06
   --------------------------- ------------ 8.7/12.6 MB 714.8 kB/s eta 0:00:06
   --------------------------- ------------ 8.7/12.6 MB 714.8 kB/s eta 0:00:06
   ---------------------------- ----------- 8.9/12.6 MB 710.7 kB/s eta 0:00:06
   ---------------------------- ----------- 8.9/12.6 MB 710.7 kB/s eta 0:00:06
   ----------------------------- ---------- 9.2/12.6 MB 705.1 kB/s eta 0:00:05
   ----------------------------- ---------- 9.2/12.6 MB 705.1 kB/s eta 0:00:05
   ------------------------------ --------- 9.4/12.6 MB 700.7 kB/s eta 0:00:05
   ------------------------------ --------- 9.4/12.6 MB 700.7 kB/s eta 0:00:05
   ------------------------------ --------- 9.4/12.6 MB 700.7 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 697.4 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 697.4 kB/s eta 0:00:05
   ------------------------------- -------- 10.0/12.6 MB 695.1 kB/s eta 0:00:04
   ------------------------------- -------- 10.0/12.6 MB 695.1 kB/s eta 0:00:04
   -------------------------------- ------- 10.2/12.6 MB 693.0 kB/s eta 0:00:04
   -------------------------------- ------- 10.2/12.6 MB 693.0 kB/s eta 0:00:04
   --------------------------------- ------ 10.5/12.6 MB 690.2 kB/s eta 0:00:04
   --------------------------------- ------ 10.5/12.6 MB 690.2 kB/s eta 0:00:04
   ---------------------------------- ----- 10.7/12.6 MB 688.3 kB/s eta 0:00:03
   ---------------------------------- ----- 10.7/12.6 MB 688.3 kB/s eta 0:00:03
   ----------------------------------- ---- 11.0/12.6 MB 686.5 kB/s eta 0:00:03
   ----------------------------------- ---- 11.0/12.6 MB 686.5 kB/s eta 0:00:03
   ----------------------------------- ---- 11.3/12.6 MB 684.1 kB/s eta 0:00:02
   ----------------------------------- ---- 11.3/12.6 MB 684.1 kB/s eta 0:00:02
   ----------------------------------- ---- 11.3/12.6 MB 684.1 kB/s eta 0:00:02
   ------------------------------------ --- 11.5/12.6 MB 674.9 kB/s eta 0:00:02
   ------------------------------------ --- 11.5/12.6 MB 674.9 kB/s eta 0:00:02
   ------------------------------------- -- 11.8/12.6 MB 668.0 kB/s eta 0:00:02
   ------------------------------------- -- 11.8/12.6 MB 668.0 kB/s eta 0:00:02
   ------------------------------------- -- 11.8/12.6 MB 668.0 kB/s eta 0:00:02
   ------------------------------------- -- 11.8/12.6 MB 668.0 kB/s eta 0:00:02
   -------------------------------------- - 12.1/12.6 MB 653.7 kB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 653.7 kB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 653.7 kB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 653.7 kB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 641.5 kB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 641.5 kB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 641.5 kB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 628.0 kB/s eta 0:00:00
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading llvmlite-0.49.0-cp312-cp312-win_amd64.whl (41.9 MB)
   ---------------------------------------- 0.0/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.9 MB ? eta -:--:--
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.5/41.9 MB 50.2 kB/s eta 0:13:43
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
    --------------------------------------- 0.8/41.9 MB 63.5 kB/s eta 0:10:47
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.0/41.9 MB 56.9 kB/s eta 0:11:57
   - -------------------------------------- 1.3/41.9 MB 60.6 kB/s eta 0:11:09
   - -------------------------------------- 1.3/41.9 MB 60.6 kB/s eta 0:11:09
   - -------------------------------------- 1.3/41.9 MB 60.6 kB/s eta 0:11:09
   - -------------------------------------- 1.3/41.9 MB 60.6 kB/s eta 0:11:09
   - -------------------------------------- 1.3/41.9 MB 60.6 kB/s eta 0:11:09
   - -------------------------------------- 1.3/41.9 MB 60.6 kB/s eta 0:11:09
   - -------------------------------------- 1.3/41.9 MB 60.6 kB/s eta 0:11:09
   - -------------------------------------- 1.3/41.9 MB 60.6 kB/s eta 0:11:09
   - -------------------------------------- 1.3/41.9 MB 60.6 kB/s eta 0:11:09
   - -------------------------------------- 1.3/41.9 MB 60.6 kB/s eta 0:11:09
   - -------------------------------------- 1.6/41.9 MB 67.9 kB/s eta 0:09:54
   - -------------------------------------- 1.6/41.9 MB 67.9 kB/s eta 0:09:54
   - -------------------------------------- 1.6/41.9 MB 67.9 kB/s eta 0:09:54
   - -------------------------------------- 1.6/41.9 MB 67.9 kB/s eta 0:09:54
   - -------------------------------------- 1.6/41.9 MB 67.9 kB/s eta 0:09:54
   - -------------------------------------- 1.6/41.9 MB 67.9 kB/s eta 0:09:54
   - -------------------------------------- 1.6/41.9 MB 67.9 kB/s eta 0:09:54
   - -------------------------------------- 1.8/41.9 MB 75.9 kB/s eta 0:08:48
   - -------------------------------------- 1.8/41.9 MB 75.9 kB/s eta 0:08:48
   - -------------------------------------- 1.8/41.9 MB 75.9 kB/s eta 0:08:48
   - -------------------------------------- 1.8/41.9 MB 75.9 kB/s eta 0:08:48
   - -------------------------------------- 1.8/41.9 MB 75.9 kB/s eta 0:08:48
   - -------------------------------------- 1.8/41.9 MB 75.9 kB/s eta 0:08:48
   -- ------------------------------------- 2.1/41.9 MB 83.5 kB/s eta 0:07:57
   -- ------------------------------------- 2.1/41.9 MB 83.5 kB/s eta 0:07:57
   -- ------------------------------------- 2.1/41.9 MB 83.5 kB/s eta 0:07:57
   -- ------------------------------------- 2.1/41.9 MB 83.5 kB/s eta 0:07:57
   -- ------------------------------------- 2.4/41.9 MB 91.1 kB/s eta 0:07:14
   -- ------------------------------------- 2.4/41.9 MB 91.1 kB/s eta 0:07:14
   -- ------------------------------------- 2.4/41.9 MB 91.1 kB/s eta 0:07:14
   -- ------------------------------------- 2.4/41.9 MB 91.1 kB/s eta 0:07:14
   -- ------------------------------------- 2.4/41.9 MB 91.1 kB/s eta 0:07:14
   -- ------------------------------------- 2.4/41.9 MB 91.1 kB/s eta 0:07:14
   -- ------------------------------------- 2.6/41.9 MB 97.7 kB/s eta 0:06:42
   -- ------------------------------------- 2.6/41.9 MB 97.7 kB/s eta 0:06:42
   -- ------------------------------------- 2.6/41.9 MB 97.7 kB/s eta 0:06:42
   -- ------------------------------------- 2.6/41.9 MB 97.7 kB/s eta 0:06:42

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
df = pd.read_csv("Messy_Student_Dataset.csv")

In [5]:
df

,Student ID,Age,Gender,Study Hours per Day,Attendance Percent,Previous Score,Internet Access,Final Result
0,S001,18,Female,2.5,88.0,72.0,Yes,Pass
1,S002,19,Male,1.0,65.0,55.0,Yes,Pass
2,S003,18,Female,4.0,95.0,84.0,Yes,Pass
3,S004,20,Male,0.5,52.0,43.0,No,Fail
4,S005,19,Female,3.0,90.0,78.0,Yes,Pass
5,S006,21,Male,NaN,70.0,61.0,Yes,Pass
6,S007,20,Female,0.8,NaN,49.0,No,Fail
7,S008,18,Male,3.5,92.0,81.0,Yes,Pass
8,S009,22,NaN,2.0,76.0,68.0,Yes,Pass
9,S010,21,Male,1.2,60.0,NaN,No,Fail
10,S011,19,FEMALE,4.5,97.0,89.0,YES,Pass
11,S012,18,male,2.8,85.0,74.0,yes,pass
12,S013,20,Female,1.0,63.0,57.0,No,Pass
13,S014,22,Male,3.2,89.0,79.0,Yes,NaN
14,S015,21,Female,0.4,48.0,41.0,No,Fail
15,S016,19,Male,2.3,80.0,69.0,Yes,Pass
16,S017,18,Female,3.8,94.0,86.0,Yes,Pass
17,S018,20,Male,0.7,55.0,46.0,No,Fail
18,S019,22,Female,2.7,83.0,73.0,Yes,Pass
19,S020,21,Male,1.8,72.0,63.0,Yes,Pass
20,S005,19,Female,3.0,90.0,78.0,Yes,Pass
21,S008,18,Male,3.5,92.0,81.0,Yes,Pass
22,S021,19,Female,2.2,82.0,71.0,yes,Pass
23,NaN,20,Male,1.4,68.0,59.0,No,Fail
24,S023,18,Female,3.1,91.0,80.0,Yes,Pass

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student ID           24 non-null     object
 1   Age                  25 non-null     int64
 2   Gender               24 non-null     object
 3   Study Hours per Day  24 non-null     float64
 4   Attendance Percent   24 non-null     float64
 5   Previous Score       24 non-null     float64
 6   Internet Access      25 non-null     object
 7   Final Result         24 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 1.7+ KB

In [7]:
df.head()

,Student ID,Age,Gender,Study Hours per Day,Attendance Percent,Previous Score,Internet Access,Final Result
0,S001,18,Female,2.5,88.0,72.0,Yes,Pass
1,S002,19,Male,1.0,65.0,55.0,Yes,Pass
2,S003,18,Female,4.0,95.0,84.0,Yes,Pass
3,S004,20,Male,0.5,52.0,43.0,No,Fail
4,S005,19,Female,3.0,90.0,78.0,Yes,Pass

In [8]:
df.tail(10)

,Student ID,Age,Gender,Study Hours per Day,Attendance Percent,Previous Score,Internet Access,Final Result
15,S016,19,Male,2.3,80.0,69.0,Yes,Pass
16,S017,18,Female,3.8,94.0,86.0,Yes,Pass
17,S018,20,Male,0.7,55.0,46.0,No,Fail
18,S019,22,Female,2.7,83.0,73.0,Yes,Pass
19,S020,21,Male,1.8,72.0,63.0,Yes,Pass
20,S005,19,Female,3.0,90.0,78.0,Yes,Pass
21,S008,18,Male,3.5,92.0,81.0,Yes,Pass
22,S021,19,Female,2.2,82.0,71.0,yes,Pass
23,NaN,20,Male,1.4,68.0,59.0,No,Fail
24,S023,18,Female,3.1,91.0,80.0,Yes,Pass

In [9]:
print(df.isnull().sum())

Student ID             1
Age                    0
Gender                 1
Study Hours per Day    1
Attendance Percent     1
Previous Score         1
Internet Access        0
Final Result           1
dtype: int64

In [10]:
df.dropna()

,Student ID,Age,Gender,Study Hours per Day,Attendance Percent,Previous Score,Internet Access,Final Result
0,S001,18,Female,2.5,88.0,72.0,Yes,Pass
1,S002,19,Male,1.0,65.0,55.0,Yes,Pass
2,S003,18,Female,4.0,95.0,84.0,Yes,Pass
3,S004,20,Male,0.5,52.0,43.0,No,Fail
4,S005,19,Female,3.0,90.0,78.0,Yes,Pass
7,S008,18,Male,3.5,92.0,81.0,Yes,Pass
10,S011,19,FEMALE,4.5,97.0,89.0,YES,Pass
11,S012,18,male,2.8,85.0,74.0,yes,pass
12,S013,20,Female,1.0,63.0,57.0,No,Pass
14,S015,21,Female,0.4,48.0,41.0,No,Fail
15,S016,19,Male,2.3,80.0,69.0,Yes,Pass
16,S017,18,Female,3.8,94.0,86.0,Yes,Pass
17,S018,20,Male,0.7,55.0,46.0,No,Fail
18,S019,22,Female,2.7,83.0,73.0,Yes,Pass
19,S020,21,Male,1.8,72.0,63.0,Yes,Pass
20,S005,19,Female,3.0,90.0,78.0,Yes,Pass
21,S008,18,Male,3.5,92.0,81.0,Yes,Pass
22,S021,19,Female,2.2,82.0,71.0,yes,Pass
24,S023,18,Female,3.1,91.0,80.0,Yes,Pass

In [11]:
print(df.isnull().sum())

Student ID             1
Age                    0
Gender                 1
Study Hours per Day    1
Attendance Percent     1
Previous Score         1
Internet Access        0
Final Result           1
dtype: int64